version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "AutoscalingStack"
s3_bucket = "autoscaling"
s3_prefix = "AutoscalingStack"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
